### ISSUE TITLE
Root element ignored in options, full path returned

### ISSUE THREAD

**Issue by lilacdev** [fczbkk/css-selector-generator#78]
Context page : `http://histo.io`

Code to execute in order to test it (x = 165, y = 305):

```js
function testCase(x, y) {
  const root = document.querySelector('nav > ul > li > ul');
  const result = CssSelectorGenerator.getCssSelector(document.elementFromPoint(x, y), { blacklist: ['[href=*]', '[src=*]'], root: root });
  console.log(result);
  // :root > :nth-child(2) > :nth-child(4) > :nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(2) > :nth-child(5) > :nth-child(1);
}
```

**Comment by lilacdev** [comment]
I have to add that result could "almost" work with only this part of selector `:nth-child(5) > :nth-child(1)`. A better one could be `:nth-child(5) > a`.

**Comment by fczbkk** [comment]
@lilacdev What selector do you expect to be a result of this?

**Comment by fczbkk** [comment]
@lilacdev This was caused by a combination of two bugs:

- descendant selectors were never tried except when producing fallback selector
- root element was considered when generating selector candidates, but ignored during final testing of selector validity

Both issues should are fixed in `v3.4.1`. Please update and it should work correctly.

**Comment by lilacdev** [comment]
Thanks for quick reply. Unfortunately error still here (I doubled checked I was using version 3.4.1).
